name: Deploy to Server

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # REPOSITORY      : username/repository-name
      # REPOSITORY_NAME : repository-name
      # BRANCH          : master
      # DIR_NAME        : repository-name@master

      - name: Extract Repository and Branch name
        run: |
          REPOSITORY=${{ github.repository }}
          REPOSITORY_NAME=$(echo $REPOSITORY | cut -d'/' -f2)
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Extract Etc
        env:
          DIR_NAME: ${{ env.REPOSITORY_NAME }}@${{ env.BRANCH }}
        run: |
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV
      - name: Remove Previous Repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.DIR_NAME }}
            docker-compose stop
            cd ..
            rm -rf ${{ env.DIR_NAME }}
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
#           envkey_TOKEN: ${{ secrets.TOKEN }}
#           envkey_LOG_SERVER: ${{ secrets.LOG_SERVER }}
#           envkey_LOG_SERVER_MESSAGE_CHANNEL: ${{ secrets.LOG_SERVER_MESSAGE_CHANNEL }}
#           envkey_LOG_SERVER_USER_STATUS_CHANNEL: ${{ secrets.LOG_SERVER_USER_STATUS_CHANNEL }}
#           envkey_LOG_SERVER_USER_GAME_CHANNEL: ${{ secrets.LOG_SERVER_USER_GAME_CHANNEL }}
#           envkey_LOG_SERVER_BOT_LOG_CHANNEL: ${{ secrets.LOG_SERVER_BOT_LOG_CHANNEL }}
          file_name: .env

      - name: Upload Repository
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./**
          target: ${{ env.DIR_NAME }}

      - name: Launch as Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.DIR_NAME }}
            docker-compose up --build -d
